services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Derhansen\FormCrshield\:
    resource: '../Classes/*'

  Derhansen\FormCrshield\Hooks\Form:
    public: true

  Derhansen\FormCrshield\Service\ChallengeResponseService:
    public: true

